name: Deploy Spring Boot to Aliyun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Spring Boot Docker image
      run: |
        docker build -t my-springboot-app .
        docker tag my-springboot-app:latest registry.cn-hangzhou.aliyuncs.com/my-repository/my-springboot-app:latest

    - name: Log in to Aliyun Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Push Docker image to Aliyun Container Registry
      run: |
        docker push registry.cn-hangzhou.aliyuncs.com/my-repository/my-springboot-app:latest

    - name: Deploy Spring Boot to ECS
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.ALIYUN_SSH_KEY }} root@<YOUR_ALIYUN_IP> 'docker pull registry.cn-hangzhou.aliyuncs.com/my-repository/my-springboot-app:latest && docker run -d -p 8080:8080 my-springboot-app'
